### ISSUE TITLE
Crashing on onCreate() Application

### ISSUE THREAD

**Issue by dev-myatminsoe** [MatthiasRobbers/shortbread#7] opened 2017-02-26 05:18 UTC
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
                      at shortbread.Shortbread.setShortcuts(Shortbread.java:66)
                      at shortbread.Shortbread.create(Shortbread.java:48)
                      at com.popstack.mvoter2015.MVoterApp.onCreate(MVoterApp.java:22)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method)

**Comment by dev-myatminsoe** [comment] 2017-02-26 05:21
I'm using AppCompact Activity.

**Comment by MatthiasRobbers** [comment] 2017-02-26 11:39
Duplicate of #5. It would be great if you could add more info about your `build.gradle` on that issue so it can be fixed.

**Closed as completed by MatthiasRobbers** 2017-02-26 11:39 UTC
Labels: duplicate

**Comment by MatthiasRobbers** [comment] 2017-02-27 21:58
@septemberboy7 there is now a solution in the linked issue.
