### ISSUE TITLE
Ability to remove and add shortcuts [Enhancement]

### ISSUE THREAD

**Issue by Akshshr** [MatthiasRobbers/shortbread#22] opened 2018-05-07 13:25 UTC
Hey there, cool lib! 

Not sure if this is the same as Dynamic shortcuts, but essentially adding and removing shortcuts from the application. 

Most apps are very dynamic and change views/layouts based on conditions..this would be really helpful

Regards

**Comment by Akshshr** [comment] 2018-05-07 14:04
[ISSUE]

Annotating methods in Java 8 isn't being supported by the way, works on an activity level though

**Comment by MatthiasRobbers** [comment] 2018-05-08 21:34
Hey, thanks! I think that is indeed a duplicate of #3.

**Closed as completed by MatthiasRobbers** 2018-05-08 21:34 UTC
